// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview This file defines a Genkit flow that suggests poses based on the number of people detected in the camera frame.
 *
 * - `suggestPoses` - An async function that takes the number of people as input and returns a list of suggested poses.
 * - `SuggestPosesInput` - The input type for the `suggestPoses` function, defining the number of people in the frame.
 * - `SuggestPosesOutput` - The output type for the `suggestPoses` function, providing an array of suggested poses.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestPosesInputSchema = z.object({
  numberOfPeople: z.number().describe('The number of people detected in the camera frame.'),
});
export type SuggestPosesInput = z.infer<typeof SuggestPosesInputSchema>;

const SuggestPosesOutputSchema = z.object({
  suggestedPoses: z.array(z.string()).describe('An array of suggested poses suitable for the detected number of people.'),
});
export type SuggestPosesOutput = z.infer<typeof SuggestPosesOutputSchema>;

export async function suggestPoses(input: SuggestPosesInput): Promise<SuggestPosesOutput> {
  return suggestPosesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestPosesPrompt',
  input: {schema: SuggestPosesInputSchema},
  output: {schema: SuggestPosesOutputSchema},
  prompt: `You are an AI posing assistant that specializes in suggesting poses for photos based on the number of people in the frame.

  Suggest poses that are natural, flattering, and easy to achieve.

  Here's the number of people in the photo: {{{numberOfPeople}}}

  Suggest poses:
  `,
});

const suggestPosesFlow = ai.defineFlow(
  {
    name: 'suggestPosesFlow',
    inputSchema: SuggestPosesInputSchema,
    outputSchema: SuggestPosesOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
